"""Build Agent — genera build Pathfinder 1E usando RAG + LLM."""
import json
import os
import re
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..rag.generator import get_provider
from ..rag.retriever import Retriever

from .builder_benchmarks import (
    class_good_saves,
    compute_benchmarks,
    evaluate_build,
    estimated_hp,
    format_benchmarks_for_prompt,
    focus_guidance,
)


def _reference_dir() -> Path:
    return Path(__file__).resolve().parent.parent.parent / "data" / "reference"


def _load_reference_index(reference_dir: Path) -> dict[str, dict[str, dict]]:
    """Carica il catalogo reference in un indice source_id -> {type, name}."""
    index: dict[str, dict[str, dict]] = {"feat": {}, "spell": {}, "item": {}}
    for kind, fname in [("feat", "ogl/feats.json"), ("spell", "ogl/spells.json"), ("item", "ogl/items.json")]:
        path = reference_dir / fname
        if not path.exists():
            continue
        try:
            data = json.load(open(path, encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        entries = data if isinstance(data, list) else data.get("entries", [])
        for e in entries:
            sid = e.get("source_id", "")
            if sid:
                index[kind][sid] = {"name": e.get("name", ""), "source_id": sid}
    return index


def _load_reference_names(reference_dir: Path) -> dict[str, list[dict]]:
    names = {"feat": [], "spell": [], "item": []}
    for kind, fname in [("feat", "ogl/feats.json"), ("spell", "ogl/spells.json"), ("item", "ogl/items.json")]:
        path = reference_dir / fname
        if not path.exists():
            continue
        data = json.load(open(path, encoding="utf-8"))
        entries = data if isinstance(data, list) else data.get("entries", [])
        for e in entries:
            text = f"{e.get('name', '')} {e.get('prerequisites', '')} {' '.join(e.get('tags', []))}"
            names[kind].append({"source_id": e.get("source_id", ""), "name": e.get("name", ""), "text": text.lower()})
    return names


def _find_reference_entries(query: str, reference_dir: Path, top_k: int = 10) -> list[dict]:
    """Keyword search sul catalogo reference per trovare voci compatibili."""
    query_terms = set(re.findall(r"[a-zA-Z0-9]+", query.lower()))
    refs = _load_reference_names(reference_dir)
    scored = []
    for kind, entries in refs.items():
        for e in entries:
            if not e["source_id"]:
                continue
            terms = set(re.findall(r"[a-zA-Z0-9]+", e["text"]))
            score = len(query_terms & terms)
            # bonus se un termine della query compare nel nome esatto
            name_terms = set(re.findall(r"[a-zA-Z0-9]+", e["name"].lower()))
            score += len(query_terms & name_terms)
            if score > 0:
                scored.append((score, {"source_id": e["source_id"], "type": kind, "name": e["name"]}))
    scored.sort(key=lambda x: (x[0], x[1]["name"].lower()), reverse=True)
    return [x[1] for x in scored[:top_k]]


def _build_target_schema() -> dict[str, Any]:
    return {
        "build_id": "stringa univoca",
        "class": "classe richiesta",
        "mode": "full-pg",
        "request": {"class": "...", "race": "...", "level": 5, "focus": "...", "archetype": "..."},
        "build_state": {
            "class": "...",
            "mode": "full-pg",
            "race": "...",
            "archetype": "...",
            "step": 1,
            "step_total": 1,
            "step_labels": {"1": "Generated by LLM agent"},
            "version": "2026.04.03"
        },
        "benchmark": {
            "meta_tier": "T1/T2/T3/T4",
            "statistics": {"PF": 0, "CA": 0, "DPR": 0, "saves": {"Tempra": 0, "Riflessi": 0, "Volonta": 0}}
        },
        "export": {
            "sheet_locale": "it-IT",
            "markdown": "riassunto testuale della build"
        },
        "catalog_references": [{"source_id": "...", "type": "feat|spell|item", "name": "..."}],
        "reference_catalog_version": "2026.04.03",
        "step_audit": {
            "request_timestamp": "ISO8601",
            "client_fingerprint_hash": "a1b2c3d4e5f6789012345678abcdef01",
            "outcome": "accepted",
            "attempt_count": 1,
            "backoff_reason": None
        }
    }


def _make_prompt(request: dict, context_chunks: list[dict], references: list[dict]) -> str:
    schema = json.dumps(_build_target_schema(), ensure_ascii=False, indent=2)
    chunks_text = "\n\n---\n\n".join(c["text"] for c in context_chunks)
    refs_text = "\n".join(f"- [{r['type']}] {r['name']} ({r['source_id']})" for r in references)
    req_text = json.dumps(request, ensure_ascii=False, indent=2)
    benchmarks = compute_benchmarks(
        request.get("level", 5),
        request.get("focus"),
    )
    benchmark_text = format_benchmarks_for_prompt(benchmarks)
    focus_text = focus_guidance(request.get("focus"))["priority"]
    return (
        "Sei un esperto costruttore di personaggi Pathfinder 1E. "
        "Genera una build completa in formato JSON puro (nessun testo extra) "
        "rispettando esattamente questa struttura:\n\n"
        f"{schema}\n\n"
        f"{benchmark_text}\n\n"
        f"{focus_text}\n\n"
        "Usa SOLO talenti, incantesimi e oggetti dal catalogo reference fornito. "
        "Se non conosci un valore, usa 0 o null, ma non inventare source_id. "
        "Tutti i source_id in catalog_references DEVONO corrispondere ESATTAMENTE a uno degli source_id elencati nel catalogo fornito. "
        "NON usare abbreviazioni di libro come PHB, CRB, APG come source_id. "
        "step_audit.client_fingerprint_hash DEVE essere una stringa esadecimale di 32 caratteri (esempio: a1b2c3d4e5f6789012345678abcdef01). "
        "Le statistiche in benchmark.statistics DEVONO essere realistiche per il livello e rispettare i target sopra.\n\n"
        "Contesto dai moduli:\n"
        f"{chunks_text}\n\n"
        "Catalogo reference disponibile:\n"
        f"{refs_text}\n\n"
        "Richiesta utente:\n"
        f"{req_text}\n\n"
        "Risposta JSON:"
    )


def _extract_json(text: str) -> dict | None:
    # try whole text first
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    # try fenced code block
    m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            pass
    # try first { ... }
    m = re.search(r"(\{.*\})", text, re.DOTALL)
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            pass
    return None


def _load_reference_entries(reference_dir: Path | None = None) -> dict[str, dict[str, dict]]:
    """Carica catalogo come type -> {source_id -> entry}."""
    result: dict[str, dict[str, dict]] = {"feat": {}, "spell": {}, "item": {}}
    for kind, fname in [("feat", "ogl/feats.json"), ("spell", "ogl/spells.json"), ("item", "ogl/items.json")]:
        path = (reference_dir or _reference_dir()) / fname
        if not path.exists():
            continue
        try:
            data = json.load(open(path, encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        entries = data if isinstance(data, list) else data.get("entries", [])
        for e in entries:
            sid = e.get("source_id", "")
            if sid:
                result[kind][sid] = e
    return result


def _normalize_name(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", name.lower())


def _is_generic_source_id(sid: str) -> bool:
    """Source_id troppo generici spesso generati dal LLM invece di identificatori veri."""
    if not sid:
        return True
    return sid.upper() in {"CRB", "AUTO", "CORE", "PHB", "MM", "DMG", "APG", "UM", "UC", "ARG", "ACG", "OA", "UI", "HA", "MA", "GD"}


def _resolve_catalog_references(payload: dict, reference_dir: Path | None = None) -> dict:
    """Risolve source_id errati/inventati mappando per nome; rimuove ref non risolvibili."""
    refs = payload.get("catalog_references") or []
    if not refs:
        return payload
    entries = _load_reference_entries(reference_dir or _reference_dir())
    resolved = []
    for ref in refs:
        ref_type = ref.get("type")
        if ref_type not in entries:
            continue
        sid = ref.get("source_id", "")
        name = ref.get("name", "")
        # Se source_id valido e non generico, usa quello
        if sid and sid in entries[ref_type] and not _is_generic_source_id(sid):
            resolved.append({
                "source_id": sid,
                "type": ref_type,
                "name": entries[ref_type][sid].get("name", name),
            })
            continue
        # Prova a risolvere per nome
        norm_name = _normalize_name(name)
        match = None
        if norm_name:
            # match esatto normalizzato
            for sid2, entry in entries[ref_type].items():
                if _is_generic_source_id(sid2):
                    continue
                if _normalize_name(entry.get("name", "")) == norm_name:
                    match = (sid2, entry)
                    break
            # fallback: nome contenuto
            if not match:
                for sid2, entry in entries[ref_type].items():
                    if _is_generic_source_id(sid2):
                        continue
                    entry_name = _normalize_name(entry.get("name", ""))
                    if norm_name in entry_name or entry_name in norm_name:
                        match = (sid2, entry)
                        break
        if match:
            resolved.append({"source_id": match[0], "type": ref_type, "name": match[1].get("name", name)})
    # Se pochissime ref, aggiungi default valide
    if len(resolved) < 2:
        for sid, entry in entries.get("feat", {}).items():
            if len(resolved) >= 3:
                break
            if _is_generic_source_id(sid):
                continue
            resolved.append({"source_id": sid, "type": "feat", "name": entry.get("name", "")})
    payload["catalog_references"] = resolved[:8]
    return payload


def _ensure_fingerprint(payload: dict) -> dict:
    """Garantisce che client_fingerprint_hash sia una stringa di almeno 32 caratteri."""
    audit = payload.get("step_audit") or {}
    fp = audit.get("client_fingerprint_hash", "")
    if not isinstance(fp, str) or len(fp) < 32:
        audit["client_fingerprint_hash"] = uuid.uuid4().hex
        payload["step_audit"] = audit
    return payload


def _validate_catalog_references(payload: dict, reference_dir: Path | None = None) -> list[str]:
    """Verifica che i catalog_references esistano effettivamente nel catalogo reference."""
    errors: list[str] = []
    refs = payload.get("catalog_references") or []
    if not refs:
        return errors
    index = _load_reference_index(reference_dir or _reference_dir())
    for ref in refs:
        ref_type = ref.get("type")
        sid = ref.get("source_id")
        if not ref_type or ref_type not in index:
            errors.append(f"catalog_reference tipo non valido: {ref_type}")
            continue
        if not sid:
            errors.append("catalog_reference con source_id mancante")
            continue
        if sid not in index[ref_type]:
            errors.append(f"catalog_reference non trovata in catalogo: {ref_type}::{sid}")
    return errors


def _validate_numerical_constraints(payload: dict) -> list[str]:
    """Verifica che le statistiche siano realistiche per livello/focus."""
    errors: list[str] = []
    request = payload.get("request") or {}
    level = request.get("level", 5)
    focus = request.get("focus")
    benchmark = payload.get("benchmark") or {}
    stats = benchmark.get("statistics") or {}

    try:
        targets = compute_benchmarks(level, focus)
    except Exception:
        return errors

    pf = stats.get("PF")
    ca = stats.get("CA")
    dpr = stats.get("DPR")
    saves = stats.get("saves") or {}

    if pf is not None:
        if pf < 0:
            errors.append(f"PF negativo: {pf}")
        elif pf > targets["hp"]["blue"] * 2:
            errors.append(f"PF irrealisticamente alto per livello {level}: {pf} (target blue {targets['hp']['blue']})")

    if ca is not None:
        if ca < 0:
            errors.append(f"CA negativa: {ca}")
        elif ca > targets["ac"]["blue"] + 10:
            errors.append(f"CA irrealistica per livello {level}: {ca} (target blue {targets['ac']['blue']})")

    if dpr is not None:
        if dpr < 0:
            errors.append(f"DPR negativo: {dpr}")
        elif dpr > targets["dpr"]["blue"] * 3:
            errors.append(f"DPR irrealistico per livello {level}: {dpr} (target blue {targets['dpr']['blue']})")

    for save_name in ("Tempra", "Riflessi", "Volonta"):
        val = saves.get(save_name)
        if val is None:
            continue
        if val < 0:
            errors.append(f"Salvataggio {save_name} irrealistico (negativo): {val}")
        elif val > targets["saves"]["blue"] + 10:
            errors.append(f"Salvataggio {save_name} irrealisticamente alto per livello {level}: {val}")

    return errors


def _annotate_with_evaluation(payload: dict) -> dict:
    """Aggiunge benchmark_evaluation ricalcolando tier e note."""
    request = payload.get("request") or {}
    level = request.get("level", 5)
    focus = request.get("focus")
    benchmark_payload = payload.get("benchmark") or {}
    stats = benchmark_payload.get("statistics") or {}
    if not stats:
        return payload
    try:
        targets = compute_benchmarks(level, focus)
        evaluation = evaluate_build(stats, targets, focus)
        payload["benchmark_evaluation"] = evaluation
        # Aggiorna meta_tier se presente in benchmark.
        if "benchmark" in payload:
            payload["benchmark"]["meta_tier"] = evaluation["meta_tier"]
    except Exception:
        pass
    return payload


def _validate(payload: dict) -> list[str]:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "tools"))
    from generate_build_db import validate_with_schema

    error = validate_with_schema(
        "build_core.schema.json",
        payload,
        "build agent output",
        strict=False,
    )
    return [error] if error else []


def _build_fallback(request: dict, references: list[dict]) -> dict:
    """Fallback deterministico/mock che produce un payload valido coerente con i benchmark."""
    now = datetime.now(timezone.utc).isoformat()
    level = request.get("level", 5)
    focus = request.get("focus")
    class_name = request.get("class", "Fighter")
    benchmarks = compute_benchmarks(level, focus)

    # Scegli target green/orange in base al focus per il fallback.
    focus_l = (focus or "balanced").lower()
    if focus_l == "dpr":
        target_pf = benchmarks["hp"]["orange"]
        target_ca = benchmarks["ac"]["orange"]
        target_dpr = benchmarks["dpr"]["green"]
    elif focus_l == "tank":
        target_pf = benchmarks["hp"]["green"]
        target_ca = benchmarks["ac"]["green"]
        target_dpr = benchmarks["dpr"]["orange"]
    elif focus_l == "control":
        target_pf = benchmarks["hp"]["orange"]
        target_ca = benchmarks["ac"]["orange"]
        target_dpr = benchmarks["dpr"]["red"]  # DPR non rilevante per control
    elif focus_l == "support":
        target_pf = benchmarks["hp"]["orange"]
        target_ca = benchmarks["ac"]["orange"]
        target_dpr = benchmarks["dpr"]["red"]  # DPR non rilevante per support
    else:
        target_pf = benchmarks["hp"]["orange"]
        target_ca = benchmarks["ac"]["orange"]
        target_dpr = benchmarks["dpr"]["orange"]

    # Stima PF realistica per classe.
    estimated = estimated_hp(level, class_name, con_mod=2)
    target_pf = max(target_pf, estimated)

    good = class_good_saves(class_name)
    stats = {
        "PF": int(target_pf),
        "CA": int(target_ca),
        "DPR": round(float(target_dpr), 1),
        "saves": {
            "Tempra": benchmarks["saves"]["green"] if "Tempra" in good else benchmarks["saves"]["orange"],
            "Riflessi": benchmarks["saves"]["green"] if "Riflessi" in good else benchmarks["saves"]["orange"],
            "Volonta": benchmarks["saves"]["green"] if "Volonta" in good else benchmarks["saves"]["orange"],
        },
    }
    evaluation = evaluate_build(stats, benchmarks, focus)

    # Filtra solo reference esistenti.
    ref_dir = _reference_dir()
    index = _load_reference_index(ref_dir)
    valid_refs = []
    for r in references[:8]:
        if r.get("source_id") and r.get("type") in index and r["source_id"] in index[r["type"]]:
            valid_refs.append(r)
    if not valid_refs:
        # Cerca reference di default nel catalogo.
        for sid, entry in index.get("feat", {}).items():
            if "power" in entry.get("name", "").lower():
                valid_refs.append({"source_id": sid, "type": "feat", "name": entry["name"]})
                break
        if not valid_refs and index.get("feat"):
            first = next(iter(index["feat"].values()))
            valid_refs.append({"source_id": first["source_id"], "type": "feat", "name": first["name"]})

    payload = {
        "build_id": f"gen-{uuid.uuid4().hex[:12]}",
        "class": class_name,
        "mode": "full-pg",
        "request": request,
        "build_state": {
            "class": class_name,
            "mode": "full-pg",
            "race": request.get("race"),
            "archetype": request.get("archetype"),
            "step": 1,
            "step_total": 1,
            "step_labels": {"1": "Generated by LLM agent"},
            "version": "2026.04.03"
        },
        "benchmark": {
            "meta_tier": evaluation["meta_tier"],
            "statistics": stats
        },
        "benchmark_evaluation": evaluation,
        "export": {
            "sheet_locale": "it-IT",
            "markdown": f"Build {class_name} {request.get('race', 'Human')} livello {level} (focus {focus_l}). "
                        "Generata dal Build Agent MVP con benchmark per livello."
        },
        "catalog_references": valid_refs[:5],
        "reference_catalog_version": "2026.04.03",
        "step_audit": {
            "request_timestamp": now,
            "client_fingerprint_hash": "mock" * 8,
            "outcome": "accepted",
            "attempt_count": 1,
            "backoff_reason": None
        },
        "validation_status": "passed",
    }
    payload = _ensure_fingerprint(payload)
    payload = _resolve_catalog_references(payload, ref_dir)
    return payload


def generate_build(request: dict, retriever: Retriever | None = None, provider_name: str | None = None, max_retries: int = 2) -> dict:
    """Genera una build PF1e valida usando RAG + LLM, con validazione numerica e catalogo."""
    provider = get_provider(provider_name)
    ref_dir = _reference_dir()

    if provider.__class__.__name__ == "MockProvider":
        refs = _find_reference_entries(
            f"{request.get('class', '')} {request.get('race', '')} {request.get('focus', '')}",
            ref_dir
        )
        return _build_fallback(request, refs)

    query = f"{request.get('class', '')} {request.get('race', '')} {request.get('archetype', '')} {request.get('focus', '')} Pathfinder 1E build"
    context = retriever.search(query, top_k=5) if retriever else []
    refs = _find_reference_entries(query, ref_dir, top_k=15)

    errors_history = []
    for attempt in range(1, max_retries + 1):
        prompt = _make_prompt(request, context, refs)
        if errors_history:
            prompt += f"\n\nErrori precedenti da correggere:\n{json.dumps(errors_history, ensure_ascii=False)}"
        raw = provider.generate(prompt, [])
        payload = _extract_json(raw)
        if payload is None:
            errors_history.append("Risposta non è JSON valido")
            continue
        payload = _ensure_fingerprint(payload)
        payload = _resolve_catalog_references(payload, ref_dir)
        errors = _validate(payload)
        errors.extend(_validate_catalog_references(payload, ref_dir))
        errors.extend(_validate_numerical_constraints(payload))
        if not errors:
            payload = _annotate_with_evaluation(payload)
            payload["validation_status"] = "passed"
            return payload
        errors_history.extend(errors)

    # fallback after retries
    fallback = _build_fallback(request, refs)
    fallback["validation_status"] = "failed"
    fallback["_validation_errors"] = errors_history
    return fallback
