"""Build Agent — genera build Pathfinder 1E usando RAG + LLM."""
import json
import os
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..rag.generator import get_provider
from ..rag.retriever import Retriever


def _load_reference_names(reference_dir: Path) -> dict[str, list[dict]]:
    names = {"feat": [], "spell": [], "item": []}
    for kind, fname in [("feat", "feats.json"), ("spell", "spells.json"), ("item", "items.json")]:
        path = reference_dir / fname
        if not path.exists():
            continue
        data = json.load(open(path, encoding="utf-8"))
        entries = data if isinstance(data, list) else data.get("entries", [])
        for e in entries:
            text = f"{e.get('name', '')} {e.get('prerequisites', '')} {' '.join(e.get('tags', []))}"
            names[kind].append({"source_id": e.get("source_id", ""), "name": e.get("name", ""), "text": text.lower()})
    return names


def _find_reference_entries(query: str, reference_dir: Path, top_k: int = 10) -> list[dict]:
    """Keyword search sul catalogo reference per trovare voci compatibili."""
    query_terms = set(re.findall(r"[a-zA-Z0-9]+", query.lower()))
    refs = _load_reference_names(reference_dir)
    scored = []
    for kind, entries in refs.items():
        for e in entries:
            if not e["source_id"]:
                continue
            terms = set(re.findall(r"[a-zA-Z0-9]+", e["text"]))
            score = len(query_terms & terms)
            if score > 0:
                scored.append((score, {"source_id": e["source_id"], "type": kind, "name": e["name"]}))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [x[1] for x in scored[:top_k]]


def _build_target_schema() -> dict[str, Any]:
    return {
        "build_id": "stringa univoca",
        "class": "classe richiesta",
        "mode": "full-pg",
        "request": {"class": "...", "race": "...", "level": 5, "focus": "...", "archetype": "..."},
        "build_state": {
            "class": "...",
            "mode": "full-pg",
            "race": "...",
            "archetype": "...",
            "step": 1,
            "step_total": 1,
            "step_labels": {"1": "Generated by LLM agent"},
            "version": "2026.04.03"
        },
        "benchmark": {
            "meta_tier": "T1/T2/T3/T4",
            "statistics": {"PF": 0, "CA": 0, "DPR": 0, "saves": {"Tempra": 0, "Riflessi": 0, "Volonta": 0}}
        },
        "export": {
            "sheet_locale": "it-IT",
            "markdown": "riassunto testuale della build"
        },
        "catalog_references": [{"source_id": "...", "type": "feat|spell|item", "name": "..."}],
        "reference_catalog_version": "2026.04.03",
        "step_audit": {
            "request_timestamp": "ISO8601",
            "client_fingerprint_hash": "stringa di almeno 32 caratteri",
            "outcome": "accepted",
            "attempt_count": 1,
            "backoff_reason": None
        }
    }


def _make_prompt(request: dict, context_chunks: list[dict], references: list[dict]) -> str:
    schema = json.dumps(_build_target_schema(), ensure_ascii=False, indent=2)
    chunks_text = "\n\n---\n\n".join(c["text"] for c in context_chunks)
    refs_text = "\n".join(f"- [{r['type']}] {r['name']} ({r['source_id']})" for r in references)
    req_text = json.dumps(request, ensure_ascii=False, indent=2)
    return (
        "Sei un esperto costruttore di personaggi Pathfinder 1E. "
        "Genera una build completa in formato JSON puro (nessun testo extra) "
        "rispettando esattamente questa struttura:\n\n"
        f"{schema}\n\n"
        "Usa SOLO talenti, incantesimi e oggetti dal catalogo reference fornito. "
        "Se non conosci un valore, usa 0 o null, ma non inventare source_id.\n\n"
        "Contesto dai moduli:\n"
        f"{chunks_text}\n\n"
        "Catalogo reference disponibile:\n"
        f"{refs_text}\n\n"
        "Richiesta utente:\n"
        f"{req_text}\n\n"
        "Risposta JSON:"
    )


def _extract_json(text: str) -> dict | None:
    # try whole text first
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    # try fenced code block
    m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            pass
    # try first { ... }
    m = re.search(r"(\{.*\})", text, re.DOTALL)
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            pass
    return None


def _validate(payload: dict) -> list[str]:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "tools"))
    from generate_build_db import validate_with_schema

    error = validate_with_schema(
        "build_core.schema.json",
        payload,
        "build agent output",
        strict=False,
    )
    return [error] if error else []


def _build_fallback(request: dict, references: list[dict]) -> dict:
    """Fallback deterministico/mock che produce un payload valido."""
    now = datetime.now(timezone.utc).isoformat()
    return {
        "build_id": f"gen-{uuid.uuid4().hex[:12]}",
        "class": request.get("class", "Fighter"),
        "mode": "full-pg",
        "request": request,
        "build_state": {
            "class": request.get("class", "Fighter"),
            "mode": "full-pg",
            "race": request.get("race"),
            "archetype": request.get("archetype"),
            "step": 1,
            "step_total": 1,
            "step_labels": {"1": "Generated by LLM agent"},
            "version": "2026.04.03"
        },
        "benchmark": {
            "meta_tier": "T2",
            "statistics": {
                "PF": 45,
                "CA": 18,
                "DPR": 15,
                "saves": {"Tempra": 7, "Riflessi": 3, "Volonta": 2}
            }
        },
        "export": {
            "sheet_locale": "it-IT",
            "markdown": f"Build {request.get('class', 'Fighter')} {request.get('race', 'Human')} livello {request.get('level', 5)}. "
                        "Generata dal Build Agent MVP."
        },
        "catalog_references": references[:5] or [{"source_id": "power_attack", "type": "feat", "name": "Power Attack"}],
        "reference_catalog_version": "2026.04.03",
        "step_audit": {
            "request_timestamp": now,
            "client_fingerprint_hash": "mock" * 8,
            "outcome": "accepted",
            "attempt_count": 1,
            "backoff_reason": None
        }
    }


def generate_build(request: dict, retriever: Retriever | None = None, provider_name: str | None = None, max_retries: int = 2) -> dict:
    """Genera una build PF1e valida usando RAG + LLM."""
    provider = get_provider(provider_name)

    if getattr(provider, "__class__.__name__", None) == "MockProvider":
        refs = _find_reference_entries(
            f"{request.get('class', '')} {request.get('race', '')} {request.get('focus', '')}",
            Path(__file__).resolve().parent.parent.parent / "data" / "reference"
        )
        return _build_fallback(request, refs)

    query = f"{request.get('class', '')} {request.get('race', '')} {request.get('archetype', '')} {request.get('focus', '')} Pathfinder 1E build"
    context = retriever.search(query, top_k=5) if retriever else []
    refs = _find_reference_entries(query, Path(__file__).resolve().parent.parent.parent / "data" / "reference", top_k=15)

    errors_history = []
    for attempt in range(1, max_retries + 1):
        prompt = _make_prompt(request, context, refs)
        if errors_history:
            prompt += f"\n\nErrori precedenti da correggere:\n{json.dumps(errors_history, ensure_ascii=False)}"
        raw = provider.generate(prompt, [])
        payload = _extract_json(raw)
        if payload is None:
            errors_history.append("Risposta non è JSON valido")
            continue
        errors = _validate(payload)
        if not errors:
            payload["validation_status"] = "passed"
            return payload
        errors_history.extend(errors)

    # fallback after retries
    fallback = _build_fallback(request, refs)
    fallback["validation_status"] = "failed"
    fallback["_validation_errors"] = errors_history
    return fallback
